cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    akash:
      email: akashreji647@gmail.com
      first_name: Akash
      last_name: Reji
      logged_in: false
      password: $2b$12$jErTnT9vmhscNQUamL3yeuDLtbk9Yr7PB5WKJZoS2Obwh2HGiJSYy
      password_hint: reji
      roles: null
preauthorized:
  emails: []
